name: cosaapp
description: "Cosa Application Glucosa Control"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  dio: ^5.3.2
  intl: ^0.18.1
  flutter_blue_plus: ^1.5.2
  shared_preferences: ^2.4.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  permission_handler: ^11.3.1
  connectivity_plus: ^5.0.0
  mobile_scanner: ^3.5.6
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/maskot_cosaapp.png"

flutter:
  assets:
   - assets/images/cosaapp.png
   - assets/images/profile.png
  uses-material-design: true